- name: Download Kafka {{ kafka_version }}
  get_url: url=http://mirror.catn.com/pub/apache/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz dest=/tmp/kafka_2.11-{{ kafka_version }}.tgz mode=0644 force=no

- name: Unpack the tar
  shell: tar -xzvf /tmp/kafka_2.11-{{ kafka_version }}.tgz chdir=/tmp/

- name: Copy Kafka into place
  shell: mv /tmp/kafka_2.11-{{ kafka_version }} /usr/local/kafka-{{ kafka_version }} creates=/usr/local/kafka-{{ kafka_version }}

- name: Symlink /usr/local/kafka to this version
  shell: ln -s kafka-{{ kafka_version }} kafka chdir=/usr/local creates=/usr/local/kafka

- name: Copy the config file for brokers
  template: src=conf/server.properties dest=/usr/local/kafka/config/server-{{ item.key }}.properties mode=0644
  with_dict: "{{ kafka_brokers }}"

- name: Install the Kafka upstart service handler
  template: src=upstart/kafka.conf dest=/etc/init/ mode=0755
  with_dict: "{{ kafka_brokers }}"

- name: Run the kafka service
  service: name=kafka state=started enabled=yes
